name: Shared lib

on:
  push:
    paths:
      - "services/shared/**"
    branches:
      - main
  pull_request:
    paths:
      - "services/shared/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: services/shared
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run ci
